import React from "react";
import Link from "next/link";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@app/api/auth/[...nextauth]/route";
import Image from "next/image";
import Course from "@models/Course";
import CourseItem from "@components/CourseItem";

export const metadata = {
  title: "Profile",
  description: "Generated by Pemuja GKM",
};

const page = async () => {
  const session = await getServerSession(authOptions);
  const courses = await Course.find().select("title");
  return (
    <div className="flex flex-row h-screen pl-28 pt-20 pb-12">
      <div className="flex flex-col w-4/12 gap-4 ">
        <div className="flex flex-row gap-8 items-center">
          <Image
            className="border-4 rounded-lg border-slate-600"
            src={session.user.image}
            alt="profile"
            height={100}
            width={100}
          />
          <div className="flex flex-col">
            <h3 className="font-semibold">{session.user.name}</h3>
          </div>
        </div>
        <div className="flex flex-col gap-2 p-4 border-2 border-slate-400 rounded-lg flex-1">
          <h3>Your Name</h3>
          <h3 className="flex py-2 px-4 rounded-lg border-2 border-slate-400">
            {session.user.name}
          </h3>
          <h3>Email</h3>
          <h3 className="flex py-2 px-4 rounded-lg border-2 border-slate-400">
            {session.user.email}
          </h3>
          <h3>Phone Number</h3>
          <h3 className="flex py-2 px-4 rounded-lg border-2 border-slate-400">
            {session.user.name}
          </h3>
        </div>
      </div>
      <div className="flex flex-col px-8 w-8/12 gap-4">
        <h2 className="font-semibold text-3xl">Courses</h2>
        <div className="flex flex-1 flex-col p-4 border-4 rounded-lg gap-4 border-slate-400">
          <h3 className="flex items-center gap-2 text-lg font-semibold">
            Finished
            <span className="bg-green-400 text-slate-100 p-1 flex items-center justify-center text-lg h-8 w-8 rounded-lg">
              7
            </span>
          </h3>
          <div className="flex flex-row items-center gap-4">
            {courses.map((val) => (
              <CourseItem
                title={val.title}
                className="p-2 h-32 w-32 border-4 bg-blue-100 rounded-lg"
              />
            ))}
          </div>
        </div>
        <div className="flex flex-1 flex-col p-4 border-4 rounded-lg gap-4 border-slate-400">
          <h3 className="flex items-center gap-2 text-lg font-semibold">
            Unfinished
            <span className="bg-slate-600 text-slate-100 p-1 flex items-center justify-center text-lg h-8 w-8 rounded-lg">
              7
            </span>
          </h3>
          <div className="flex flex-row items-center gap-4">
            {courses.map((val) => (
              <CourseItem
                title={val.title}
                className="p-2 h-32 w-32 border-4 bg-blue-100 rounded-lg"
              />
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

export default page;
