import Discussion from "@models/Discussion";
import React from "react";

export const metadata = {
  title: "Forum",
  description: "Generated by Pemuja GKM",
};

const page = async () => {
  const discussion = await Discussion.find();
  return (
    <div className="flex flex-row h-screen pl-32 pt-20 pb-12">
      <div className="flex flex-col w-3/12 gap-8">
        <button className="greenButton h-12 text-slate-100 duration-200 rounded-md">
          Create Discussion
        </button>
        <div className="flex flex-col border-4 gap-2 border-slate-700 rounded-xl py-4 px-8">
          <h3 className="font-semibold">Filter Discussion</h3>
          <div className="flex flex-row gap-4">
            <input className="rounded-full" type="checkbox" name="latest" />
            <label htmlFor="latest">Latest</label>
          </div>
          <div className="flex flex-row gap-4">
            <input className="rounded-full" type="checkbox" name="latest" />
            <label htmlFor="latest">Latest</label>
          </div>
          <hr className="my-2" />
          <div className="flex flex-row gap-4">
            <input className="rounded-full" type="checkbox" name="latest" />
            <label htmlFor="latest">Latest</label>
          </div>
          <div className="flex flex-row gap-4">
            <input className="rounded-full" type="checkbox" name="latest" />
            <label htmlFor="latest">Latest</label>
          </div>
        </div>
      </div>
      {/* {discussion.map((val) => (
        <div className="flex flex-col">
          <h3>{val.title}</h3>
          <p>{val.desc}</p>
          <p>{val.sender}</p>
          <p>
            {val.hashtags.map((val) => (
              <p>{val}</p>
            ))}
          </p>
          <p>
            {val.comments.map((val) => (
              <>
                <p>{val.sender}</p>
                <p>{val.comment}</p>
              </>
            ))}
          </p>
        </div>
      ))} */}
    </div>
  );
};

export default page;
