import React from "react";
import styles from "@styles/Exercise.module.css";

export const metadata = {
  title: "Exercise",
  description: "Generated by Pemuja GKM",
};

const page = () => {
  return (
    <div className="flex flex-col h-screen pl-28 pt-20">
      <h3 className={styles.asd}>page</h3>
    </div>
  );
};

export default page;
