import Nav from "@components/Nav";
import Image from "next/image";

import React from "react";

export const metadata = {
  title: "Doo-IT",
  description: "Generated by Pemuja GKM",
};

const Home = () => {
  return (
    <section>
      <Nav />
      <div>AAAAAAAAAAAaaaaaaaaaaaaaaaaaaaaa</div>
    </section>
  );
};

export default Home;
