import Nav from "@components/Nav";
import Image from "next/image";
import LandingIMG from "@assets/LandingIMG.png";

import React from "react";
import Link from "next/link";

export const metadata = {
  title: "Doo-IT",
  description: "Generated by Pemuja GKM",
};

const Home = () => {
  return (
    <section>
      <Nav />
      <div className="flex flex-row px-20 h-screen">
        <div className="w-1/2 flex flex-col pt-8 gap-4  text-slate-800 justify-center">
          <h2 className="text-2xl font-semibold">
            Hi, Welcome to Doo-IT E-Learning!
          </h2>
          <h1 className="text-6xl font-black">
            Best IT <br />
            Online Course
          </h1>
          <h2 className="text-2xl font-semibold">
            Doo-IT provides general knowledge to help <br /> increase your
            insight.
          </h2>
          <Link
            href={"/register"}
            className="greenButton w-max py-2 px-4 rounded-full text-slate-100 duration-200 font-semibold"
          >
            Get Started
          </Link>
        </div>
        <div className="w-1/2 items-center flex p-12">
          <Image
            src={LandingIMG}
            alt="landingIMG"
            height={1000}
            width={1000}
            className="w-full"
          />
        </div>
      </div>
    </section>
  );
};

export default Home;
