import Image from "next/image";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@app/api/auth/[...nextauth]/route";
import SignOut from "./SignOut";

export const metadata = {
  title: "Login",
  description: "Generated by Pemuja GKM",
};

const Topbar = async () => {
  const session = await getServerSession(authOptions);

  return (
    <div className="flex flex-row justify-between items-center fixed px-8 h-20 w-full z-10">
      <div className="flex flex-row gap-4 items-center">
        <button className="h-12 w-12 p-2 hover:bg-slate-200 duration-300 rounded-full">
          <svg
            fill="currentColor"
            className="w-full h-full"
            viewBox="0 0 16 16"
          >
            <path
              fillRule="evenodd"
              d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"
            />
          </svg>
        </button>
      </div>
      <div className="flex flex-row gap-4 items-center">
        <h3>Halo, {session.user.name}</h3>
        <Image
          className="rounded-full"
          src={session.user.image}
          width={48}
          height={48}
          alt="Course Item"
        />
        <SignOut />
      </div>
    </div>
  );
};

export default Topbar;
