import Nav from "@components/Nav";
import React from "react";
import { getServerSession } from "next-auth/next";
import { redirect } from "next/navigation";
import { authOptions } from "@app/api/auth/[...nextauth]/route";

export const metadata = {
  title: "Register",
  description: "Generated by Pemuja GKM",
};

const page = async () => {
  const session = await getServerSession(authOptions);

  if (session) {
    redirect("/dashboard");
  }
  return (
    <div>
      <Nav />
    </div>
  );
};

export default page;
