import Sidebar from "@/components/Sidebar";
import Topbar from "@/components/Topbar";

export const metadata = {
  title: "Dashboard",
  description: "Generated by Pemuja GKM",
};

export default function layout({ children }) {
  return (
    <div>
      <Topbar />
      <Sidebar />
      <div className="pl-28 pt-20 ">{children}</div>
    </div>
  );
}
