import Sidebar from "@/components/Sidebar";
import Topbar from "@/components/Topbar";
import { getServerSession } from "next-auth/next";
import { redirect } from "next/navigation";
import { authOptions } from "@app/api/auth/[...nextauth]/route";

export const metadata = {
  title: "Dashboard",
  description: "Generated by Pemuja GKM",
};

export default async function layout({ children }) {
  const session = await getServerSession(authOptions);

  if (!session) {
    redirect("/");
  }

  // if (false) {
  //   redirect("/");
  // }

  return (
    <div className="relative">
      <Topbar />
      <Sidebar />
      {children}
      {/* <div className="pl-28 pt-20 ">{children}</div> */}
    </div>
  );
}
